V1.0.0
roleplayreality/DiscordSollicitatieBot pull request #1
Opened 2024-05-18 20:33 UTC by Draakjestam

aub lieve maikel <3

2024-05-18 20:36 UTC, DoJoMan18 commented on logger.js
> +    const channel = client.channels.cache.get(process.env.BOT_LOG_CHANNEL_ID);
Idee om via een webhook logs te sturen? Dit geeft je ruimte indien bijvoorbeeld de bot om 1 of ander reden het kanaal niet kan vinden. Of de discord api kapot is.

2024-05-18 20:42 UTC, DoJoMan18 commented on package.json
> +  "license": "ISC",
Wat is een ISC license?

2024-05-18 20:44 UTC, DoJoMan18 commented on index.js
> +                logIntaketoChannel(client, `Tried to make a new channel but user with ID "${results[i].discord}" is not in the Discord server.`, [255, 0, 0]);
Wat nou als iemand uberhaubt niet de server in kan (NAL ban ofzo), Blijft dit bericht gespamd worden?

2024-05-18 20:47 UTC, DoJoMan18 requested changes
Zou je bovenstaande comments willen bekijken ;D
Wat gebeurd er overigens wanneer er een intake gaande is (kanaal is aangemaakt) en de gebruiker vertrekt de discord server? (bijvoorbeeld door een nal ban)

2024-05-18 20:50 UTC, DoJoMan18 commented on logger.js
> +        console.error('Invalid channel ID or channel type.');
Stop de code ook met draaien als dit gebeurd?
Dit ivm transcodes die ook niet meer gelogd worden lijkt mij?

2024-05-18 20:58 UTC, Draakjestam commented on logger.js
> +    const channel = client.channels.cache.get(process.env.BOT_LOG_CHANNEL_ID);
dat heb ik expres niet meer aangepast ivm verschillende opzetten van logging met de mod versie van de bot, daarbij word een webhook wat meer gezeik

2024-05-18 20:58 UTC, Draakjestam commented on package.json
> +  "license": "ISC",
auto license vanuit npm init

2024-05-18 20:59 UTC, Draakjestam commented on index.js
> +                logIntaketoChannel(client, `Tried to make a new channel but user with ID "${results[i].discord}" is not in the Discord server.`, [255, 0, 0]);
yup, mogelijk kan ik kijken of we gaan zoeken of persoon een ban heeft, mocht die gebanned zijn moete we even kijken en en wat qua communicatie RI OM?

2024-05-18 21:00 UTC, Draakjestam commented on logger.js
> +        console.error('Invalid channel ID or channel type.');
nee, transcripts worden los gestuurd in een ander kanaal

2024-05-18 21:38 UTC, DoJoMan18 commented on index.js
> +                logIntaketoChannel(client, `Tried to make a new channel but user with ID "${results[i].discord}" is not in the Discord server.`, [255, 0, 0]);
Ik zou geen communicatie doen, persoon komt zelf wel bij OM omdat hij de server niet in kan. Zou idd ff checken of persoon niet gebanned is, maar zou dit ook verder niet loggen, of enkel 1 keer. Opzich is dit wel iets waar ze als OM / TM zelf een check kunnen doen

2024-05-19 13:13 UTC, DoJoMan18 approved these changes
Lekker man!

2024-05-19 13:13 UTC, merged